#!/bin/bash
# Maintainer: Veysel Ors
# Date: 05/11/2023
# Purpose: This script aims to test the connection between github and my own shell

User="Veysel Ors"
Role="DevOps Engineer"
Company="Ors IT Solutions"

echo "This is $User from $Company. $User is a $Role at the $Company company."
